services:
  migrate:
      image: migrate/migrate:v4.19.1

      depends_on:
        db_scenarios:
          condition: service_healthy

      volumes:
        - ../../migrations/postgres:/migrations:ro

      command:
        [
          "-path=/migrations",
          "-database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_scenarios:5432/${POSTGRES_DB}?sslmode=disable",
          "up"
        ]

      restart: "no"

      networks:
      - interactive_onboarding
      profiles:
        - migrate
