import type { OnboardingScenario } from '@interactive-onboarding/shared'

const now = '2026-08-04T10:00:00.000Z'

export const defaultScenario: OnboardingScenario = {
  id: 'scenario-first-auto-listing',
  projectId: 'project-avito-demo',
  projectKey: 'avito-demo',
  flowKey: 'first-listing',
  name: 'Первое объявление: автомобиль с пробегом',
  description:
    'Помогает новому пользователю пройти публикацию первого объявления в транспортной категории.',
  status: 'published',
  version: 3,
  versionId: 'scenario-first-auto-listing-v3',
  createdAt: now,
  updatedAt: now,
  publishedAt: now,
  pages: [
    {
      id: 'page-profile',
      projectId: 'project-avito-demo',
      name: 'Профиль нового пользователя',
      description: 'Точка входа после регистрации',
      path: '/demo/profile',
      type: 'test',
    },
    {
      id: 'page-new-category',
      projectId: 'project-avito-demo',
      name: 'Выбор категории объявления',
      description: 'Список верхнеуровневых категорий',
      path: '/demo/new',
      type: 'test',
    },
    {
      id: 'page-new-transport',
      projectId: 'project-avito-demo',
      name: 'Уточнение транспорта',
      description: 'Выбор транспорта и состояния авто',
      path: '/demo/new/transport',
      type: 'test',
    },
    {
      id: 'page-new-auto',
      projectId: 'project-avito-demo',
      name: 'Форма автомобиля с пробегом',
      description: 'Полная форма объявления',
      path: '/demo/new/auto',
      type: 'test',
    },
  ],
  steps: [
    {
      id: 'step-profile-create',
      versionId: 'scenario-first-auto-listing-v3',
      pageId: 'page-profile',
      pagePath: '/demo/profile',
      order: 1,
      selector: '[data-onboarding-id="profile-create-button"]',
      title: 'Начните с первого объявления',
      body: 'После регистрации профиль пустой. Самый короткий путь к продаже начинается с кнопки размещения.',
      placement: 'top',
      completion: 'navigate',
      nextUrl: '/demo/new',
    },
    {
      id: 'step-category-transport',
      versionId: 'scenario-first-auto-listing-v3',
      pageId: 'page-new-category',
      pagePath: '/demo/new',
      order: 2,
      selector: '[data-onboarding-id="category-transport"]',
      title: 'Выберите транспорт',
      body: 'В транспорте важны дополнительные данные: тип, состояние, фото, VIN и пробег. Поэтому путь здесь подробнее.',
      placement: 'right',
      completion: 'navigate',
      nextUrl: '/demo/new/transport',
    },
    {
      id: 'step-transport-used',
      versionId: 'scenario-first-auto-listing-v3',
      pageId: 'page-new-transport',
      pagePath: '/demo/new/transport',
      order: 3,
      selector: '[data-onboarding-id="transport-used-car"]',
      title: 'Уточните тип объявления',
      body: 'Для автомобиля с пробегом откроется форма с данными, которые помогают покупателю быстрее принять решение.',
      placement: 'right',
      completion: 'navigate',
      nextUrl: '/demo/new/auto',
    },
    {
      id: 'step-auto-photos',
      versionId: 'scenario-first-auto-listing-v3',
      pageId: 'page-new-auto',
      pagePath: '/demo/new/auto',
      order: 4,
      selector: '[data-onboarding-id="auto-photos"]',
      title: 'Добавьте фото автомобиля',
      body: 'Первые фото снаружи и внутри помогают покупателю оценить состояние до переписки и осмотра.',
      placement: 'right',
      completion: 'next_button',
    },
    {
      id: 'step-auto-details',
      versionId: 'scenario-first-auto-listing-v3',
      pageId: 'page-new-auto',
      pagePath: '/demo/new/auto',
      order: 5,
      selector: '[data-onboarding-id="auto-details"]',
      title: 'Заполните данные для доверия',
      body: 'VIN, пробег и технические параметры снижают сомнения покупателя и уменьшают лишние вопросы.',
      placement: 'right',
      completion: 'next_button',
    },
    {
      id: 'step-auto-publish',
      versionId: 'scenario-first-auto-listing-v3',
      pageId: 'page-new-auto',
      pagePath: '/demo/new/auto',
      order: 6,
      selector: '[data-onboarding-id="auto-publish"]',
      title: 'Проверьте цену и опубликуйте',
      body: 'Цена, контакты и способ связи завершают объявление. После проверки его можно размещать.',
      placement: 'right',
      completion: 'next_button',
    },
  ],
}
